//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountWS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://hcsbk.kz/", ConfigurationName="AccountWS.AccountWSSoap")]
    public interface AccountWSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetClientAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountWS.GetClientAccountResponse GetClientAccount(AccountWS.GetClientAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetClientAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<AccountWS.GetClientAccountResponse> GetClientAccountAsync(AccountWS.GetClientAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetClientAccountInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountWS.GetClientAccountInfoResponse GetClientAccountInfo(AccountWS.GetClientAccountInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetClientAccountInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<AccountWS.GetClientAccountInfoResponse> GetClientAccountInfoAsync(AccountWS.GetClientAccountInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetClientAccountLogs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountWS.GetClientAccountLogsResponse GetClientAccountLogs(AccountWS.GetClientAccountLogsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetClientAccountLogs", ReplyAction="*")]
        System.Threading.Tasks.Task<AccountWS.GetClientAccountLogsResponse> GetClientAccountLogsAsync(AccountWS.GetClientAccountLogsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetClientAccountLogsKZ", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountWS.GetClientAccountLogsKZResponse GetClientAccountLogsKZ(AccountWS.GetClientAccountLogsKZRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetClientAccountLogsKZ", ReplyAction="*")]
        System.Threading.Tasks.Task<AccountWS.GetClientAccountLogsKZResponse> GetClientAccountLogsKZAsync(AccountWS.GetClientAccountLogsKZRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetLastClientAccountLogs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountWS.GetLastClientAccountLogsResponse GetLastClientAccountLogs(AccountWS.GetLastClientAccountLogsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetLastClientAccountLogs", ReplyAction="*")]
        System.Threading.Tasks.Task<AccountWS.GetLastClientAccountLogsResponse> GetLastClientAccountLogsAsync(AccountWS.GetLastClientAccountLogsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetLastClientAccountLogsKZ", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountWS.GetLastClientAccountLogsKZResponse GetLastClientAccountLogsKZ(AccountWS.GetLastClientAccountLogsKZRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetLastClientAccountLogsKZ", ReplyAction="*")]
        System.Threading.Tasks.Task<AccountWS.GetLastClientAccountLogsKZResponse> GetLastClientAccountLogsKZAsync(AccountWS.GetLastClientAccountLogsKZRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/BlockAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountWS.BlockAccountResponse BlockAccount(AccountWS.BlockAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/BlockAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<AccountWS.BlockAccountResponse> BlockAccountAsync(AccountWS.BlockAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/UnblockAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountWS.UnblockAccountResponse UnblockAccount(AccountWS.UnblockAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/UnblockAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<AccountWS.UnblockAccountResponse> UnblockAccountAsync(AccountWS.UnblockAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetAccountByAlterCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountWS.GetAccountByAlterCodeResponse GetAccountByAlterCode(AccountWS.GetAccountByAlterCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetAccountByAlterCode", ReplyAction="*")]
        System.Threading.Tasks.Task<AccountWS.GetAccountByAlterCodeResponse> GetAccountByAlterCodeAsync(AccountWS.GetAccountByAlterCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/IsAccountCorrect", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountWS.IsAccountCorrectResponse IsAccountCorrect(AccountWS.IsAccountCorrectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/IsAccountCorrect", ReplyAction="*")]
        System.Threading.Tasks.Task<AccountWS.IsAccountCorrectResponse> IsAccountCorrectAsync(AccountWS.IsAccountCorrectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/AccountBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountWS.AccountBalanceResponse AccountBalance(AccountWS.AccountBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/AccountBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<AccountWS.AccountBalanceResponse> AccountBalanceAsync(AccountWS.AccountBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetBankInfoByAccCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountWS.GetBankInfoByAccCodeResponse GetBankInfoByAccCode(AccountWS.GetBankInfoByAccCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetBankInfoByAccCode", ReplyAction="*")]
        System.Threading.Tasks.Task<AccountWS.GetBankInfoByAccCodeResponse> GetBankInfoByAccCodeAsync(AccountWS.GetBankInfoByAccCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetSpecAccountList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountWS.GetSpecAccountListResponse GetSpecAccountList(AccountWS.GetSpecAccountListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetSpecAccountList", ReplyAction="*")]
        System.Threading.Tasks.Task<AccountWS.GetSpecAccountListResponse> GetSpecAccountListAsync(AccountWS.GetSpecAccountListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/PCreateOutPay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountWS.PCreateOutPayResponse PCreateOutPay(AccountWS.PCreateOutPayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/PCreateOutPay", ReplyAction="*")]
        System.Threading.Tasks.Task<AccountWS.PCreateOutPayResponse> PCreateOutPayAsync(AccountWS.PCreateOutPayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/POperPaySts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountWS.POperPayStsResponse POperPaySts(AccountWS.POperPayStsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/POperPaySts", ReplyAction="*")]
        System.Threading.Tasks.Task<AccountWS.POperPayStsResponse> POperPayStsAsync(AccountWS.POperPayStsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/pOperStsGuide", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountWS.pOperStsGuideResponse pOperStsGuide(AccountWS.pOperStsGuideRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/pOperStsGuide", ReplyAction="*")]
        System.Threading.Tasks.Task<AccountWS.pOperStsGuideResponse> pOperStsGuideAsync(AccountWS.pOperStsGuideRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetPensionAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountWS.GetPensionAccountResponse GetPensionAccount(AccountWS.GetPensionAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetPensionAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<AccountWS.GetPensionAccountResponse> GetPensionAccountAsync(AccountWS.GetPensionAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/IsEpvPayment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountWS.IsEpvPaymentResponse IsEpvPayment(AccountWS.IsEpvPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/IsEpvPayment", ReplyAction="*")]
        System.Threading.Tasks.Task<AccountWS.IsEpvPaymentResponse> IsEpvPaymentAsync(AccountWS.IsEpvPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetPensionValAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountWS.GetPensionValAccountResponse GetPensionValAccount(AccountWS.GetPensionValAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetPensionValAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<AccountWS.GetPensionValAccountResponse> GetPensionValAccountAsync(AccountWS.GetPensionValAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/EpvPaymentInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountWS.EpvPaymentInfoResponse EpvPaymentInfo(AccountWS.EpvPaymentInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/EpvPaymentInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<AccountWS.EpvPaymentInfoResponse> EpvPaymentInfoAsync(AccountWS.EpvPaymentInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetRentalAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountWS.GetRentalAccountResponse GetRentalAccount(AccountWS.GetRentalAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetRentalAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<AccountWS.GetRentalAccountResponse> GetRentalAccountAsync(AccountWS.GetRentalAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetRentAccountLogs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountWS.GetRentAccountLogsResponse GetRentAccountLogs(AccountWS.GetRentAccountLogsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetRentAccountLogs", ReplyAction="*")]
        System.Threading.Tasks.Task<AccountWS.GetRentAccountLogsResponse> GetRentAccountLogsAsync(AccountWS.GetRentAccountLogsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hcsbk.kz/")]
    public partial class Account
    {
        
        private string accountIDField;
        
        private string codeField;
        
        private string alterCodeField;
        
        private string typeCodeField;
        
        private decimal balanceField;
        
        private string valCodeField;
        
        private System.DateTime transferDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountID
        {
            get
            {
                return this.accountIDField;
            }
            set
            {
                this.accountIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AlterCode
        {
            get
            {
                return this.alterCodeField;
            }
            set
            {
                this.alterCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TypeCode
        {
            get
            {
                return this.typeCodeField;
            }
            set
            {
                this.typeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal Balance
        {
            get
            {
                return this.balanceField;
            }
            set
            {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ValCode
        {
            get
            {
                return this.valCodeField;
            }
            set
            {
                this.valCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime TransferDate
        {
            get
            {
                return this.transferDateField;
            }
            set
            {
                this.transferDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hcsbk.kz/")]
    public partial class AccountLog
    {
        
        private string accCodeField;
        
        private System.DateTime dOperField;
        
        private decimal dtField;
        
        private decimal ktField;
        
        private string oprNameField;
        
        private string bankCodeField;
        
        private string knpField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccCode
        {
            get
            {
                return this.accCodeField;
            }
            set
            {
                this.accCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime DOper
        {
            get
            {
                return this.dOperField;
            }
            set
            {
                this.dOperField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal DT
        {
            get
            {
                return this.dtField;
            }
            set
            {
                this.dtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal KT
        {
            get
            {
                return this.ktField;
            }
            set
            {
                this.ktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string OprName
        {
            get
            {
                return this.oprNameField;
            }
            set
            {
                this.oprNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BankCode
        {
            get
            {
                return this.bankCodeField;
            }
            set
            {
                this.bankCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string knp
        {
            get
            {
                return this.knpField;
            }
            set
            {
                this.knpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hcsbk.kz/")]
    public partial class SpecAccount
    {
        
        private System.DateTime ordDateField;
        
        private string ordCodeField;
        
        private string accCodeField;
        
        private decimal accBalanceField;
        
        private string accountIDField;
        
        private string alterCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime OrdDate
        {
            get
            {
                return this.ordDateField;
            }
            set
            {
                this.ordDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OrdCode
        {
            get
            {
                return this.ordCodeField;
            }
            set
            {
                this.ordCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AccCode
        {
            get
            {
                return this.accCodeField;
            }
            set
            {
                this.accCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal AccBalance
        {
            get
            {
                return this.accBalanceField;
            }
            set
            {
                this.accBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AccountID
        {
            get
            {
                return this.accountIDField;
            }
            set
            {
                this.accountIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string AlterCode
        {
            get
            {
                return this.alterCodeField;
            }
            set
            {
                this.alterCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hcsbk.kz/")]
    public partial class ClientAccountLog
    {
        
        private System.DateTime operDateField;
        
        private decimal debitSumField;
        
        private decimal creditSumField;
        
        private string operNameField;
        
        private string loanIDField;
        
        private System.DateTime docDateField;
        
        private string docNumField;
        
        private string operTypeField;
        
        private string bankCodeField;
        
        private string benAccField;
        
        private string benNameField;
        
        private string kNPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime OperDate
        {
            get
            {
                return this.operDateField;
            }
            set
            {
                this.operDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal DebitSum
        {
            get
            {
                return this.debitSumField;
            }
            set
            {
                this.debitSumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal CreditSum
        {
            get
            {
                return this.creditSumField;
            }
            set
            {
                this.creditSumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OperName
        {
            get
            {
                return this.operNameField;
            }
            set
            {
                this.operNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LoanID
        {
            get
            {
                return this.loanIDField;
            }
            set
            {
                this.loanIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime DocDate
        {
            get
            {
                return this.docDateField;
            }
            set
            {
                this.docDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DocNum
        {
            get
            {
                return this.docNumField;
            }
            set
            {
                this.docNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string OperType
        {
            get
            {
                return this.operTypeField;
            }
            set
            {
                this.operTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string BankCode
        {
            get
            {
                return this.bankCodeField;
            }
            set
            {
                this.bankCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string BenAcc
        {
            get
            {
                return this.benAccField;
            }
            set
            {
                this.benAccField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string BenName
        {
            get
            {
                return this.benNameField;
            }
            set
            {
                this.benNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string KNP
        {
            get
            {
                return this.kNPField;
            }
            set
            {
                this.kNPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hcsbk.kz/")]
    public partial class ClientAccountInfo
    {
        
        private string colvirReferenceIDField;
        
        private string accCodeField;
        
        private string valCodeField;
        
        private string nameField;
        
        private string bALINField;
        
        private string bALOUTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ColvirReferenceID
        {
            get
            {
                return this.colvirReferenceIDField;
            }
            set
            {
                this.colvirReferenceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AccCode
        {
            get
            {
                return this.accCodeField;
            }
            set
            {
                this.accCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ValCode
        {
            get
            {
                return this.valCodeField;
            }
            set
            {
                this.valCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BALIN
        {
            get
            {
                return this.bALINField;
            }
            set
            {
                this.bALINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BALOUT
        {
            get
            {
                return this.bALOUTField;
            }
            set
            {
                this.bALOUTField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClientAccount", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetClientAccountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public string clientCode;
        
        public GetClientAccountRequest()
        {
        }
        
        public GetClientAccountRequest(string token, string clientCode)
        {
            this.token = token;
            this.clientCode = clientCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClientAccountResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetClientAccountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public AccountWS.Account GetClientAccountResult;
        
        public GetClientAccountResponse()
        {
        }
        
        public GetClientAccountResponse(AccountWS.Account GetClientAccountResult)
        {
            this.GetClientAccountResult = GetClientAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClientAccountInfo", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetClientAccountInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public string accountCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=2)]
        public System.DateTime dateFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=3)]
        public System.DateTime dateTo;
        
        public GetClientAccountInfoRequest()
        {
        }
        
        public GetClientAccountInfoRequest(string token, string accountCode, System.DateTime dateFrom, System.DateTime dateTo)
        {
            this.token = token;
            this.accountCode = accountCode;
            this.dateFrom = dateFrom;
            this.dateTo = dateTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClientAccountInfoResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetClientAccountInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public AccountWS.ClientAccountInfo GetClientAccountInfoResult;
        
        public GetClientAccountInfoResponse()
        {
        }
        
        public GetClientAccountInfoResponse(AccountWS.ClientAccountInfo GetClientAccountInfoResult)
        {
            this.GetClientAccountInfoResult = GetClientAccountInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClientAccountLogs", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetClientAccountLogsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public string accountCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=2)]
        public System.DateTime dateFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=3)]
        public System.DateTime dateTo;
        
        public GetClientAccountLogsRequest()
        {
        }
        
        public GetClientAccountLogsRequest(string token, string accountCode, System.DateTime dateFrom, System.DateTime dateTo)
        {
            this.token = token;
            this.accountCode = accountCode;
            this.dateFrom = dateFrom;
            this.dateTo = dateTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClientAccountLogsResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetClientAccountLogsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public AccountWS.ClientAccountLog[] GetClientAccountLogsResult;
        
        public GetClientAccountLogsResponse()
        {
        }
        
        public GetClientAccountLogsResponse(AccountWS.ClientAccountLog[] GetClientAccountLogsResult)
        {
            this.GetClientAccountLogsResult = GetClientAccountLogsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClientAccountLogsKZ", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetClientAccountLogsKZRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public string accountCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=2)]
        public System.DateTime dateFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=3)]
        public System.DateTime dateTo;
        
        public GetClientAccountLogsKZRequest()
        {
        }
        
        public GetClientAccountLogsKZRequest(string token, string accountCode, System.DateTime dateFrom, System.DateTime dateTo)
        {
            this.token = token;
            this.accountCode = accountCode;
            this.dateFrom = dateFrom;
            this.dateTo = dateTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClientAccountLogsKZResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetClientAccountLogsKZResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public AccountWS.ClientAccountLog[] GetClientAccountLogsKZResult;
        
        public GetClientAccountLogsKZResponse()
        {
        }
        
        public GetClientAccountLogsKZResponse(AccountWS.ClientAccountLog[] GetClientAccountLogsKZResult)
        {
            this.GetClientAccountLogsKZResult = GetClientAccountLogsKZResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLastClientAccountLogs", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetLastClientAccountLogsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public string accountCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=2)]
        public int count;
        
        public GetLastClientAccountLogsRequest()
        {
        }
        
        public GetLastClientAccountLogsRequest(string token, string accountCode, int count)
        {
            this.token = token;
            this.accountCode = accountCode;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLastClientAccountLogsResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetLastClientAccountLogsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public AccountWS.ClientAccountLog[] GetLastClientAccountLogsResult;
        
        public GetLastClientAccountLogsResponse()
        {
        }
        
        public GetLastClientAccountLogsResponse(AccountWS.ClientAccountLog[] GetLastClientAccountLogsResult)
        {
            this.GetLastClientAccountLogsResult = GetLastClientAccountLogsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLastClientAccountLogsKZ", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetLastClientAccountLogsKZRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public string accountCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=2)]
        public int count;
        
        public GetLastClientAccountLogsKZRequest()
        {
        }
        
        public GetLastClientAccountLogsKZRequest(string token, string accountCode, int count)
        {
            this.token = token;
            this.accountCode = accountCode;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLastClientAccountLogsKZResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetLastClientAccountLogsKZResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public AccountWS.ClientAccountLog[] GetLastClientAccountLogsKZResult;
        
        public GetLastClientAccountLogsKZResponse()
        {
        }
        
        public GetLastClientAccountLogsKZResponse(AccountWS.ClientAccountLog[] GetLastClientAccountLogsKZResult)
        {
            this.GetLastClientAccountLogsKZResult = GetLastClientAccountLogsKZResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BlockAccount", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class BlockAccountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public string accountCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=2)]
        public string reason;
        
        public BlockAccountRequest()
        {
        }
        
        public BlockAccountRequest(string token, string accountCode, string reason)
        {
            this.token = token;
            this.accountCode = accountCode;
            this.reason = reason;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BlockAccountResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class BlockAccountResponse
    {
        
        public BlockAccountResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UnblockAccount", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class UnblockAccountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public string accountCode;
        
        public UnblockAccountRequest()
        {
        }
        
        public UnblockAccountRequest(string token, string accountCode)
        {
            this.token = token;
            this.accountCode = accountCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UnblockAccountResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class UnblockAccountResponse
    {
        
        public UnblockAccountResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccountByAlterCode", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetAccountByAlterCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public string alterCode;
        
        public GetAccountByAlterCodeRequest()
        {
        }
        
        public GetAccountByAlterCodeRequest(string token, string alterCode)
        {
            this.token = token;
            this.alterCode = alterCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccountByAlterCodeResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetAccountByAlterCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public AccountWS.Account GetAccountByAlterCodeResult;
        
        public GetAccountByAlterCodeResponse()
        {
        }
        
        public GetAccountByAlterCodeResponse(AccountWS.Account GetAccountByAlterCodeResult)
        {
            this.GetAccountByAlterCodeResult = GetAccountByAlterCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsAccountCorrect", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class IsAccountCorrectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public string alterCode;
        
        public IsAccountCorrectRequest()
        {
        }
        
        public IsAccountCorrectRequest(string token, string alterCode)
        {
            this.token = token;
            this.alterCode = alterCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsAccountCorrectResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class IsAccountCorrectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public bool IsAccountCorrectResult;
        
        public IsAccountCorrectResponse()
        {
        }
        
        public IsAccountCorrectResponse(bool IsAccountCorrectResult)
        {
            this.IsAccountCorrectResult = IsAccountCorrectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AccountBalance", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class AccountBalanceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public string accCode;
        
        public AccountBalanceRequest()
        {
        }
        
        public AccountBalanceRequest(string token, string accCode)
        {
            this.token = token;
            this.accCode = accCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AccountBalanceResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class AccountBalanceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> AccountBalanceResult;
        
        public AccountBalanceResponse()
        {
        }
        
        public AccountBalanceResponse(System.Nullable<decimal> AccountBalanceResult)
        {
            this.AccountBalanceResult = AccountBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBankInfoByAccCode", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetBankInfoByAccCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public string accCode;
        
        public GetBankInfoByAccCodeRequest()
        {
        }
        
        public GetBankInfoByAccCodeRequest(string token, string accCode)
        {
            this.token = token;
            this.accCode = accCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBankInfoByAccCodeResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetBankInfoByAccCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string GetBankInfoByAccCodeResult;
        
        public GetBankInfoByAccCodeResponse()
        {
        }
        
        public GetBankInfoByAccCodeResponse(string GetBankInfoByAccCodeResult)
        {
            this.GetBankInfoByAccCodeResult = GetBankInfoByAccCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSpecAccountList", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetSpecAccountListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public string clientCode;
        
        public GetSpecAccountListRequest()
        {
        }
        
        public GetSpecAccountListRequest(string token, string clientCode)
        {
            this.token = token;
            this.clientCode = clientCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSpecAccountListResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetSpecAccountListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public AccountWS.SpecAccount[] GetSpecAccountListResult;
        
        public GetSpecAccountListResponse()
        {
        }
        
        public GetSpecAccountListResponse(AccountWS.SpecAccount[] GetSpecAccountListResult)
        {
            this.GetSpecAccountListResult = GetSpecAccountListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PCreateOutPay", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class PCreateOutPayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public string sKso_Code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=2)]
        public string sCha_Code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=3)]
        public string sCode_bc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=4)]
        public string sKnp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=5)]
        public string sCode_od;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=6)]
        public string sCode_be;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=7)]
        public string pDebetAcc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=8)]
        public string pCreditAcc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=9)]
        public string pCliName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=10)]
        public string pCliTaxCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=11)]
        public decimal pAmount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=12)]
        public decimal pAmountCms;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=13)]
        public string pTxt_Dscr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=14)]
        public string pTxt_Dscr_Cms;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=15)]
        public long sReferItem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=16)]
        public long sReferItemCms;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=17)]
        public string sGuide;
        
        public PCreateOutPayRequest()
        {
        }
        
        public PCreateOutPayRequest(
                    string token, 
                    string sKso_Code, 
                    string sCha_Code, 
                    string sCode_bc, 
                    string sKnp, 
                    string sCode_od, 
                    string sCode_be, 
                    string pDebetAcc, 
                    string pCreditAcc, 
                    string pCliName, 
                    string pCliTaxCode, 
                    decimal pAmount, 
                    decimal pAmountCms, 
                    string pTxt_Dscr, 
                    string pTxt_Dscr_Cms, 
                    long sReferItem, 
                    long sReferItemCms, 
                    string sGuide)
        {
            this.token = token;
            this.sKso_Code = sKso_Code;
            this.sCha_Code = sCha_Code;
            this.sCode_bc = sCode_bc;
            this.sKnp = sKnp;
            this.sCode_od = sCode_od;
            this.sCode_be = sCode_be;
            this.pDebetAcc = pDebetAcc;
            this.pCreditAcc = pCreditAcc;
            this.pCliName = pCliName;
            this.pCliTaxCode = pCliTaxCode;
            this.pAmount = pAmount;
            this.pAmountCms = pAmountCms;
            this.pTxt_Dscr = pTxt_Dscr;
            this.pTxt_Dscr_Cms = pTxt_Dscr_Cms;
            this.sReferItem = sReferItem;
            this.sReferItemCms = sReferItemCms;
            this.sGuide = sGuide;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PCreateOutPayResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class PCreateOutPayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public long sReferItem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public long sReferItemCms;
        
        public PCreateOutPayResponse()
        {
        }
        
        public PCreateOutPayResponse(long sReferItem, long sReferItemCms)
        {
            this.sReferItem = sReferItem;
            this.sReferItemCms = sReferItemCms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="POperPaySts", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class POperPayStsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public long pRefer;
        
        public POperPayStsRequest()
        {
        }
        
        public POperPayStsRequest(string token, long pRefer)
        {
            this.token = token;
            this.pRefer = pRefer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="POperPayStsResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class POperPayStsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string POperPayStsResult;
        
        public POperPayStsResponse()
        {
        }
        
        public POperPayStsResponse(string POperPayStsResult)
        {
            this.POperPayStsResult = POperPayStsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pOperStsGuide", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class pOperStsGuideRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public string sGuide;
        
        public pOperStsGuideRequest()
        {
        }
        
        public pOperStsGuideRequest(string token, string sGuide)
        {
            this.token = token;
            this.sGuide = sGuide;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pOperStsGuideResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class pOperStsGuideResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string pOperStsGuideResult;
        
        public pOperStsGuideResponse()
        {
        }
        
        public pOperStsGuideResponse(string pOperStsGuideResult)
        {
            this.pOperStsGuideResult = pOperStsGuideResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPensionAccount", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetPensionAccountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public string clientCode;
        
        public GetPensionAccountRequest()
        {
        }
        
        public GetPensionAccountRequest(string token, string clientCode)
        {
            this.token = token;
            this.clientCode = clientCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPensionAccountResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetPensionAccountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public AccountWS.Account GetPensionAccountResult;
        
        public GetPensionAccountResponse()
        {
        }
        
        public GetPensionAccountResponse(AccountWS.Account GetPensionAccountResult)
        {
            this.GetPensionAccountResult = GetPensionAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsEpvPayment", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class IsEpvPaymentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public string regnum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=2)]
        public string iin;
        
        public IsEpvPaymentRequest()
        {
        }
        
        public IsEpvPaymentRequest(string token, string regnum, string iin)
        {
            this.token = token;
            this.regnum = regnum;
            this.iin = iin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsEpvPaymentResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class IsEpvPaymentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public bool IsEpvPaymentResult;
        
        public IsEpvPaymentResponse()
        {
        }
        
        public IsEpvPaymentResponse(bool IsEpvPaymentResult)
        {
            this.IsEpvPaymentResult = IsEpvPaymentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPensionValAccount", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetPensionValAccountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public string clientCode;
        
        public GetPensionValAccountRequest()
        {
        }
        
        public GetPensionValAccountRequest(string token, string clientCode)
        {
            this.token = token;
            this.clientCode = clientCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPensionValAccountResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetPensionValAccountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public AccountWS.Account[] GetPensionValAccountResult;
        
        public GetPensionValAccountResponse()
        {
        }
        
        public GetPensionValAccountResponse(AccountWS.Account[] GetPensionValAccountResult)
        {
            this.GetPensionValAccountResult = GetPensionValAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EpvPaymentInfo", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class EpvPaymentInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public string regnum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=2)]
        public string iin;
        
        public EpvPaymentInfoRequest()
        {
        }
        
        public EpvPaymentInfoRequest(string token, string regnum, string iin)
        {
            this.token = token;
            this.regnum = regnum;
            this.iin = iin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EpvPaymentInfoResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class EpvPaymentInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public AccountWS.Account EpvPaymentInfoResult;
        
        public EpvPaymentInfoResponse()
        {
        }
        
        public EpvPaymentInfoResponse(AccountWS.Account EpvPaymentInfoResult)
        {
            this.EpvPaymentInfoResult = EpvPaymentInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRentalAccount", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetRentalAccountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public string clientCode;
        
        public GetRentalAccountRequest()
        {
        }
        
        public GetRentalAccountRequest(string token, string clientCode)
        {
            this.token = token;
            this.clientCode = clientCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRentalAccountResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetRentalAccountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public AccountWS.Account[] GetRentalAccountResult;
        
        public GetRentalAccountResponse()
        {
        }
        
        public GetRentalAccountResponse(AccountWS.Account[] GetRentalAccountResult)
        {
            this.GetRentalAccountResult = GetRentalAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRentAccountLogs", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetRentAccountLogsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public string ClientCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=2)]
        public System.DateTime fromDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=3)]
        public System.DateTime toDate;
        
        public GetRentAccountLogsRequest()
        {
        }
        
        public GetRentAccountLogsRequest(string token, string ClientCode, System.DateTime fromDate, System.DateTime toDate)
        {
            this.token = token;
            this.ClientCode = ClientCode;
            this.fromDate = fromDate;
            this.toDate = toDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRentAccountLogsResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetRentAccountLogsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public AccountWS.AccountLog[] GetRentAccountLogsResult;
        
        public GetRentAccountLogsResponse()
        {
        }
        
        public GetRentAccountLogsResponse(AccountWS.AccountLog[] GetRentAccountLogsResult)
        {
            this.GetRentAccountLogsResult = GetRentAccountLogsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface AccountWSSoapChannel : AccountWS.AccountWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class AccountWSSoapClient : System.ServiceModel.ClientBase<AccountWS.AccountWSSoap>, AccountWS.AccountWSSoap
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AccountWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(AccountWSSoapClient.GetBindingForEndpoint(endpointConfiguration), AccountWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AccountWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AccountWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public AccountWS.GetClientAccountResponse GetClientAccount(AccountWS.GetClientAccountRequest request)
        {
            return base.Channel.GetClientAccount(request);
        }
        
        public System.Threading.Tasks.Task<AccountWS.GetClientAccountResponse> GetClientAccountAsync(AccountWS.GetClientAccountRequest request)
        {
            return base.Channel.GetClientAccountAsync(request);
        }
        
        public AccountWS.GetClientAccountInfoResponse GetClientAccountInfo(AccountWS.GetClientAccountInfoRequest request)
        {
            return base.Channel.GetClientAccountInfo(request);
        }
        
        public System.Threading.Tasks.Task<AccountWS.GetClientAccountInfoResponse> GetClientAccountInfoAsync(AccountWS.GetClientAccountInfoRequest request)
        {
            return base.Channel.GetClientAccountInfoAsync(request);
        }
        
        public AccountWS.GetClientAccountLogsResponse GetClientAccountLogs(AccountWS.GetClientAccountLogsRequest request)
        {
            return base.Channel.GetClientAccountLogs(request);
        }
        
        public System.Threading.Tasks.Task<AccountWS.GetClientAccountLogsResponse> GetClientAccountLogsAsync(AccountWS.GetClientAccountLogsRequest request)
        {
            return base.Channel.GetClientAccountLogsAsync(request);
        }
        
        public AccountWS.GetClientAccountLogsKZResponse GetClientAccountLogsKZ(AccountWS.GetClientAccountLogsKZRequest request)
        {
            return base.Channel.GetClientAccountLogsKZ(request);
        }
        
        public System.Threading.Tasks.Task<AccountWS.GetClientAccountLogsKZResponse> GetClientAccountLogsKZAsync(AccountWS.GetClientAccountLogsKZRequest request)
        {
            return base.Channel.GetClientAccountLogsKZAsync(request);
        }
        
        public AccountWS.GetLastClientAccountLogsResponse GetLastClientAccountLogs(AccountWS.GetLastClientAccountLogsRequest request)
        {
            return base.Channel.GetLastClientAccountLogs(request);
        }
        
        public System.Threading.Tasks.Task<AccountWS.GetLastClientAccountLogsResponse> GetLastClientAccountLogsAsync(AccountWS.GetLastClientAccountLogsRequest request)
        {
            return base.Channel.GetLastClientAccountLogsAsync(request);
        }
        
        public AccountWS.GetLastClientAccountLogsKZResponse GetLastClientAccountLogsKZ(AccountWS.GetLastClientAccountLogsKZRequest request)
        {
            return base.Channel.GetLastClientAccountLogsKZ(request);
        }
        
        public System.Threading.Tasks.Task<AccountWS.GetLastClientAccountLogsKZResponse> GetLastClientAccountLogsKZAsync(AccountWS.GetLastClientAccountLogsKZRequest request)
        {
            return base.Channel.GetLastClientAccountLogsKZAsync(request);
        }
        
        public AccountWS.BlockAccountResponse BlockAccount(AccountWS.BlockAccountRequest request)
        {
            return base.Channel.BlockAccount(request);
        }
        
        public System.Threading.Tasks.Task<AccountWS.BlockAccountResponse> BlockAccountAsync(AccountWS.BlockAccountRequest request)
        {
            return base.Channel.BlockAccountAsync(request);
        }
        
        public AccountWS.UnblockAccountResponse UnblockAccount(AccountWS.UnblockAccountRequest request)
        {
            return base.Channel.UnblockAccount(request);
        }
        
        public System.Threading.Tasks.Task<AccountWS.UnblockAccountResponse> UnblockAccountAsync(AccountWS.UnblockAccountRequest request)
        {
            return base.Channel.UnblockAccountAsync(request);
        }
        
        public AccountWS.GetAccountByAlterCodeResponse GetAccountByAlterCode(AccountWS.GetAccountByAlterCodeRequest request)
        {
            return base.Channel.GetAccountByAlterCode(request);
        }
        
        public System.Threading.Tasks.Task<AccountWS.GetAccountByAlterCodeResponse> GetAccountByAlterCodeAsync(AccountWS.GetAccountByAlterCodeRequest request)
        {
            return base.Channel.GetAccountByAlterCodeAsync(request);
        }
        
        public AccountWS.IsAccountCorrectResponse IsAccountCorrect(AccountWS.IsAccountCorrectRequest request)
        {
            return base.Channel.IsAccountCorrect(request);
        }
        
        public System.Threading.Tasks.Task<AccountWS.IsAccountCorrectResponse> IsAccountCorrectAsync(AccountWS.IsAccountCorrectRequest request)
        {
            return base.Channel.IsAccountCorrectAsync(request);
        }
        
        public AccountWS.AccountBalanceResponse AccountBalance(AccountWS.AccountBalanceRequest request)
        {
            return base.Channel.AccountBalance(request);
        }
        
        public System.Threading.Tasks.Task<AccountWS.AccountBalanceResponse> AccountBalanceAsync(AccountWS.AccountBalanceRequest request)
        {
            return base.Channel.AccountBalanceAsync(request);
        }
        
        public AccountWS.GetBankInfoByAccCodeResponse GetBankInfoByAccCode(AccountWS.GetBankInfoByAccCodeRequest request)
        {
            return base.Channel.GetBankInfoByAccCode(request);
        }
        
        public System.Threading.Tasks.Task<AccountWS.GetBankInfoByAccCodeResponse> GetBankInfoByAccCodeAsync(AccountWS.GetBankInfoByAccCodeRequest request)
        {
            return base.Channel.GetBankInfoByAccCodeAsync(request);
        }
        
        public AccountWS.GetSpecAccountListResponse GetSpecAccountList(AccountWS.GetSpecAccountListRequest request)
        {
            return base.Channel.GetSpecAccountList(request);
        }
        
        public System.Threading.Tasks.Task<AccountWS.GetSpecAccountListResponse> GetSpecAccountListAsync(AccountWS.GetSpecAccountListRequest request)
        {
            return base.Channel.GetSpecAccountListAsync(request);
        }
        
        public AccountWS.PCreateOutPayResponse PCreateOutPay(AccountWS.PCreateOutPayRequest request)
        {
            return base.Channel.PCreateOutPay(request);
        }
        
        public System.Threading.Tasks.Task<AccountWS.PCreateOutPayResponse> PCreateOutPayAsync(AccountWS.PCreateOutPayRequest request)
        {
            return base.Channel.PCreateOutPayAsync(request);
        }
        
        public AccountWS.POperPayStsResponse POperPaySts(AccountWS.POperPayStsRequest request)
        {
            return base.Channel.POperPaySts(request);
        }
        
        public System.Threading.Tasks.Task<AccountWS.POperPayStsResponse> POperPayStsAsync(AccountWS.POperPayStsRequest request)
        {
            return base.Channel.POperPayStsAsync(request);
        }
        
        public AccountWS.pOperStsGuideResponse pOperStsGuide(AccountWS.pOperStsGuideRequest request)
        {
            return base.Channel.pOperStsGuide(request);
        }
        
        public System.Threading.Tasks.Task<AccountWS.pOperStsGuideResponse> pOperStsGuideAsync(AccountWS.pOperStsGuideRequest request)
        {
            return base.Channel.pOperStsGuideAsync(request);
        }
        
        public AccountWS.GetPensionAccountResponse GetPensionAccount(AccountWS.GetPensionAccountRequest request)
        {
            return base.Channel.GetPensionAccount(request);
        }
        
        public System.Threading.Tasks.Task<AccountWS.GetPensionAccountResponse> GetPensionAccountAsync(AccountWS.GetPensionAccountRequest request)
        {
            return base.Channel.GetPensionAccountAsync(request);
        }
        
        public AccountWS.IsEpvPaymentResponse IsEpvPayment(AccountWS.IsEpvPaymentRequest request)
        {
            return base.Channel.IsEpvPayment(request);
        }
        
        public System.Threading.Tasks.Task<AccountWS.IsEpvPaymentResponse> IsEpvPaymentAsync(AccountWS.IsEpvPaymentRequest request)
        {
            return base.Channel.IsEpvPaymentAsync(request);
        }
        
        public AccountWS.GetPensionValAccountResponse GetPensionValAccount(AccountWS.GetPensionValAccountRequest request)
        {
            return base.Channel.GetPensionValAccount(request);
        }
        
        public System.Threading.Tasks.Task<AccountWS.GetPensionValAccountResponse> GetPensionValAccountAsync(AccountWS.GetPensionValAccountRequest request)
        {
            return base.Channel.GetPensionValAccountAsync(request);
        }
        
        public AccountWS.EpvPaymentInfoResponse EpvPaymentInfo(AccountWS.EpvPaymentInfoRequest request)
        {
            return base.Channel.EpvPaymentInfo(request);
        }
        
        public System.Threading.Tasks.Task<AccountWS.EpvPaymentInfoResponse> EpvPaymentInfoAsync(AccountWS.EpvPaymentInfoRequest request)
        {
            return base.Channel.EpvPaymentInfoAsync(request);
        }
        
        public AccountWS.GetRentalAccountResponse GetRentalAccount(AccountWS.GetRentalAccountRequest request)
        {
            return base.Channel.GetRentalAccount(request);
        }
        
        public System.Threading.Tasks.Task<AccountWS.GetRentalAccountResponse> GetRentalAccountAsync(AccountWS.GetRentalAccountRequest request)
        {
            return base.Channel.GetRentalAccountAsync(request);
        }
        
        public AccountWS.GetRentAccountLogsResponse GetRentAccountLogs(AccountWS.GetRentAccountLogsRequest request)
        {
            return base.Channel.GetRentAccountLogs(request);
        }
        
        public System.Threading.Tasks.Task<AccountWS.GetRentAccountLogsResponse> GetRentAccountLogsAsync(AccountWS.GetRentAccountLogsRequest request)
        {
            return base.Channel.GetRentAccountLogsAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AccountWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AccountWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AccountWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://192.168.55.27/TestCBSProxyWS/AccountWS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.AccountWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://192.168.55.27/TestCBSProxyWS/AccountWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            AccountWSSoap,
            
            AccountWSSoap12,
        }
    }
}
