//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpayAuctionWs
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://hcsbk.kz/", ConfigurationName="EpayAuctionWs.EPay_AuctionWSSoap")]
    public interface EPay_AuctionWSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/StartPayment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EPayKKBOutput))]
        EpayAuctionWs.StartPaymentResponse StartPayment(EpayAuctionWs.StartPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/StartPayment", ReplyAction="*")]
        System.Threading.Tasks.Task<EpayAuctionWs.StartPaymentResponse> StartPaymentAsync(EpayAuctionWs.StartPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetPendingPayments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EPayKKBOutput))]
        EpayAuctionWs.GetPendingPaymentsResponse GetPendingPayments(EpayAuctionWs.GetPendingPaymentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetPendingPayments", ReplyAction="*")]
        System.Threading.Tasks.Task<EpayAuctionWs.GetPendingPaymentsResponse> GetPendingPaymentsAsync(EpayAuctionWs.GetPendingPaymentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/AcceptPayment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EPayKKBOutput))]
        EpayAuctionWs.AcceptPaymentResponse AcceptPayment(EpayAuctionWs.AcceptPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/AcceptPayment", ReplyAction="*")]
        System.Threading.Tasks.Task<EpayAuctionWs.AcceptPaymentResponse> AcceptPaymentAsync(EpayAuctionWs.AcceptPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/RefundPayment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EPayKKBOutput))]
        EpayAuctionWs.RefundPaymentResponse RefundPayment(EpayAuctionWs.RefundPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/RefundPayment", ReplyAction="*")]
        System.Threading.Tasks.Task<EpayAuctionWs.RefundPaymentResponse> RefundPaymentAsync(EpayAuctionWs.RefundPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetOrderStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EPayKKBOutput))]
        EpayAuctionWs.GetOrderStatusResponse GetOrderStatus(EpayAuctionWs.GetOrderStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/GetOrderStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<EpayAuctionWs.GetOrderStatusResponse> GetOrderStatusAsync(EpayAuctionWs.GetOrderStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/Z160EPayCreate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EPayKKBOutput))]
        EpayAuctionWs.Z160EPayCreateResponse Z160EPayCreate(EpayAuctionWs.Z160EPayCreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/Z160EPayCreate", ReplyAction="*")]
        System.Threading.Tasks.Task<EpayAuctionWs.Z160EPayCreateResponse> Z160EPayCreateAsync(EpayAuctionWs.Z160EPayCreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/PCreatePay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EPayKKBOutput))]
        EpayAuctionWs.PCreatePayResponse PCreatePay(EpayAuctionWs.PCreatePayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/PCreatePay", ReplyAction="*")]
        System.Threading.Tasks.Task<EpayAuctionWs.PCreatePayResponse> PCreatePayAsync(EpayAuctionWs.PCreatePayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/PCreatePayGuide", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EPayKKBOutput))]
        EpayAuctionWs.PCreatePayGuideResponse PCreatePayGuide(EpayAuctionWs.PCreatePayGuideRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/PCreatePayGuide", ReplyAction="*")]
        System.Threading.Tasks.Task<EpayAuctionWs.PCreatePayGuideResponse> PCreatePayGuideAsync(EpayAuctionWs.PCreatePayGuideRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/PCreateComisPay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EPayKKBOutput))]
        EpayAuctionWs.PCreateComisPayResponse PCreateComisPay(EpayAuctionWs.PCreateComisPayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/PCreateComisPay", ReplyAction="*")]
        System.Threading.Tasks.Task<EpayAuctionWs.PCreateComisPayResponse> PCreateComisPayAsync(EpayAuctionWs.PCreateComisPayRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://epay.hcsbk.kz/")]
    public partial class EPayAucInput
    {
        
        private int auctionIDField;
        
        private string clientCodeField;
        
        private string clientEMailField;
        
        private decimal sumField;
        
        private string paymentTypeField;
        
        private string commentField;
        
        private string backURLField;
        
        private int sourceIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int AuctionID
        {
            get
            {
                return this.auctionIDField;
            }
            set
            {
                this.auctionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ClientCode
        {
            get
            {
                return this.clientCodeField;
            }
            set
            {
                this.clientCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ClientEMail
        {
            get
            {
                return this.clientEMailField;
            }
            set
            {
                this.clientEMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Sum
        {
            get
            {
                return this.sumField;
            }
            set
            {
                this.sumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PaymentType
        {
            get
            {
                return this.paymentTypeField;
            }
            set
            {
                this.paymentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string BackURL
        {
            get
            {
                return this.backURLField;
            }
            set
            {
                this.backURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int SourceID
        {
            get
            {
                return this.sourceIDField;
            }
            set
            {
                this.sourceIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EPayKKBOutput2))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://epay.hcsbk.kz/")]
    public partial class EPayKKBOutput
    {
        
        private string actionResultUrlField;
        
        private string signedXmlField;
        
        private string clientEMailField;
        
        private string backLinkField;
        
        private string failureBackLinkField;
        
        private string postLinkField;
        
        private string failurePostLinkField;
        
        private string appendixXmlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ActionResultUrl
        {
            get
            {
                return this.actionResultUrlField;
            }
            set
            {
                this.actionResultUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SignedXml
        {
            get
            {
                return this.signedXmlField;
            }
            set
            {
                this.signedXmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ClientEMail
        {
            get
            {
                return this.clientEMailField;
            }
            set
            {
                this.clientEMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BackLink
        {
            get
            {
                return this.backLinkField;
            }
            set
            {
                this.backLinkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FailureBackLink
        {
            get
            {
                return this.failureBackLinkField;
            }
            set
            {
                this.failureBackLinkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PostLink
        {
            get
            {
                return this.postLinkField;
            }
            set
            {
                this.postLinkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string FailurePostLink
        {
            get
            {
                return this.failurePostLinkField;
            }
            set
            {
                this.failurePostLinkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string AppendixXml
        {
            get
            {
                return this.appendixXmlField;
            }
            set
            {
                this.appendixXmlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://epay.hcsbk.kz/")]
    public partial class EPayKKBOutput2 : EPayKKBOutput
    {
        
        private int orderIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int OrderID
        {
            get
            {
                return this.orderIDField;
            }
            set
            {
                this.orderIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StartPayment", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class StartPaymentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public EpayAuctionWs.EPayAucInput input;
        
        public StartPaymentRequest()
        {
        }
        
        public StartPaymentRequest(string token, EpayAuctionWs.EPayAucInput input)
        {
            this.token = token;
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StartPaymentResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class StartPaymentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public EpayAuctionWs.EPayKKBOutput2 StartPaymentResult;
        
        public StartPaymentResponse()
        {
        }
        
        public StartPaymentResponse(EpayAuctionWs.EPayKKBOutput2 StartPaymentResult)
        {
            this.StartPaymentResult = StartPaymentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPendingPayments", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetPendingPaymentsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        public GetPendingPaymentsRequest()
        {
        }
        
        public GetPendingPaymentsRequest(string token)
        {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPendingPaymentsResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetPendingPaymentsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public int[] GetPendingPaymentsResult;
        
        public GetPendingPaymentsResponse()
        {
        }
        
        public GetPendingPaymentsResponse(int[] GetPendingPaymentsResult)
        {
            this.GetPendingPaymentsResult = GetPendingPaymentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AcceptPayment", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class AcceptPaymentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public int orderID;
        
        public AcceptPaymentRequest()
        {
        }
        
        public AcceptPaymentRequest(string token, int orderID)
        {
            this.token = token;
            this.orderID = orderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AcceptPaymentResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class AcceptPaymentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public bool AcceptPaymentResult;
        
        public AcceptPaymentResponse()
        {
        }
        
        public AcceptPaymentResponse(bool AcceptPaymentResult)
        {
            this.AcceptPaymentResult = AcceptPaymentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RefundPayment", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class RefundPaymentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public int orderID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=2)]
        public string refundReason;
        
        public RefundPaymentRequest()
        {
        }
        
        public RefundPaymentRequest(string token, int orderID, string refundReason)
        {
            this.token = token;
            this.orderID = orderID;
            this.refundReason = refundReason;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RefundPaymentResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class RefundPaymentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public bool RefundPaymentResult;
        
        public RefundPaymentResponse()
        {
        }
        
        public RefundPaymentResponse(bool RefundPaymentResult)
        {
            this.RefundPaymentResult = RefundPaymentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrderStatus", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetOrderStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public int orderID;
        
        public GetOrderStatusRequest()
        {
        }
        
        public GetOrderStatusRequest(string token, int orderID)
        {
            this.token = token;
            this.orderID = orderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrderStatusResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class GetOrderStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string GetOrderStatusResult;
        
        public GetOrderStatusResponse()
        {
        }
        
        public GetOrderStatusResponse(string GetOrderStatusResult)
        {
            this.GetOrderStatusResult = GetOrderStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z160EPayCreate", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class Z160EPayCreateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public char sType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=2)]
        public string sRefer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=3)]
        public decimal pAmount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=4)]
        public decimal pCmsAmount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=5)]
        public decimal pPayAmount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=6)]
        public string pIDN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=7)]
        public string pTxt_Dscr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=8)]
        public string sAccOthers;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> sReferItem;
        
        public Z160EPayCreateRequest()
        {
        }
        
        public Z160EPayCreateRequest(string token, char sType, string sRefer, decimal pAmount, decimal pCmsAmount, decimal pPayAmount, string pIDN, string pTxt_Dscr, string sAccOthers, System.Nullable<int> sReferItem)
        {
            this.token = token;
            this.sType = sType;
            this.sRefer = sRefer;
            this.pAmount = pAmount;
            this.pCmsAmount = pCmsAmount;
            this.pPayAmount = pPayAmount;
            this.pIDN = pIDN;
            this.pTxt_Dscr = pTxt_Dscr;
            this.sAccOthers = sAccOthers;
            this.sReferItem = sReferItem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Z160EPayCreateResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class Z160EPayCreateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public int Z160EPayCreateResult;
        
        public Z160EPayCreateResponse()
        {
        }
        
        public Z160EPayCreateResponse(int Z160EPayCreateResult)
        {
            this.Z160EPayCreateResult = Z160EPayCreateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PCreatePay", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class PCreatePayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public string sKso_Code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=2)]
        public string sCha_Code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=3)]
        public string sCode_bc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=4)]
        public string sKnp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=5)]
        public string sCode_od;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=6)]
        public string sCode_be;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=7)]
        public string pDebetAcc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=8)]
        public string pCreditAcc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=9)]
        public decimal pAmount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=10)]
        public string pTxt_Dscr;
        
        public PCreatePayRequest()
        {
        }
        
        public PCreatePayRequest(string token, string sKso_Code, string sCha_Code, string sCode_bc, string sKnp, string sCode_od, string sCode_be, string pDebetAcc, string pCreditAcc, decimal pAmount, string pTxt_Dscr)
        {
            this.token = token;
            this.sKso_Code = sKso_Code;
            this.sCha_Code = sCha_Code;
            this.sCode_bc = sCode_bc;
            this.sKnp = sKnp;
            this.sCode_od = sCode_od;
            this.sCode_be = sCode_be;
            this.pDebetAcc = pDebetAcc;
            this.pCreditAcc = pCreditAcc;
            this.pAmount = pAmount;
            this.pTxt_Dscr = pTxt_Dscr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PCreatePayResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class PCreatePayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public int PCreatePayResult;
        
        public PCreatePayResponse()
        {
        }
        
        public PCreatePayResponse(int PCreatePayResult)
        {
            this.PCreatePayResult = PCreatePayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PCreatePayGuide", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class PCreatePayGuideRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public string sKso_Code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=2)]
        public string sCha_Code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=3)]
        public string sCode_bc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=4)]
        public string sKnp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=5)]
        public string sCode_od;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=6)]
        public string sCode_be;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=7)]
        public string pDebetAcc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=8)]
        public string pCreditAcc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=9)]
        public decimal pAmount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=10)]
        public string pTxt_Dscr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=11)]
        public string sGuide;
        
        public PCreatePayGuideRequest()
        {
        }
        
        public PCreatePayGuideRequest(string token, string sKso_Code, string sCha_Code, string sCode_bc, string sKnp, string sCode_od, string sCode_be, string pDebetAcc, string pCreditAcc, decimal pAmount, string pTxt_Dscr, string sGuide)
        {
            this.token = token;
            this.sKso_Code = sKso_Code;
            this.sCha_Code = sCha_Code;
            this.sCode_bc = sCode_bc;
            this.sKnp = sKnp;
            this.sCode_od = sCode_od;
            this.sCode_be = sCode_be;
            this.pDebetAcc = pDebetAcc;
            this.pCreditAcc = pCreditAcc;
            this.pAmount = pAmount;
            this.pTxt_Dscr = pTxt_Dscr;
            this.sGuide = sGuide;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PCreatePayGuideResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class PCreatePayGuideResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public long PCreatePayGuideResult;
        
        public PCreatePayGuideResponse()
        {
        }
        
        public PCreatePayGuideResponse(long PCreatePayGuideResult)
        {
            this.PCreatePayGuideResult = PCreatePayGuideResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PCreateComisPay", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class PCreateComisPayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public string sKso_Code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=2)]
        public string sCha_Code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=3)]
        public string sCode_bc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=4)]
        public string sKnp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=5)]
        public string sCode_od;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=6)]
        public string sCode_be;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=7)]
        public string pDebetAcc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=8)]
        public string pCreditAcc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=9)]
        public decimal pAmount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=10)]
        public string pTxt_Dscr;
        
        public PCreateComisPayRequest()
        {
        }
        
        public PCreateComisPayRequest(string token, string sKso_Code, string sCha_Code, string sCode_bc, string sKnp, string sCode_od, string sCode_be, string pDebetAcc, string pCreditAcc, decimal pAmount, string pTxt_Dscr)
        {
            this.token = token;
            this.sKso_Code = sKso_Code;
            this.sCha_Code = sCha_Code;
            this.sCode_bc = sCode_bc;
            this.sKnp = sKnp;
            this.sCode_od = sCode_od;
            this.sCode_be = sCode_be;
            this.pDebetAcc = pDebetAcc;
            this.pCreditAcc = pCreditAcc;
            this.pAmount = pAmount;
            this.pTxt_Dscr = pTxt_Dscr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PCreateComisPayResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class PCreateComisPayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public int PCreateComisPayResult;
        
        public PCreateComisPayResponse()
        {
        }
        
        public PCreateComisPayResponse(int PCreateComisPayResult)
        {
            this.PCreateComisPayResult = PCreateComisPayResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface EPay_AuctionWSSoapChannel : EpayAuctionWs.EPay_AuctionWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class EPay_AuctionWSSoapClient : System.ServiceModel.ClientBase<EpayAuctionWs.EPay_AuctionWSSoap>, EpayAuctionWs.EPay_AuctionWSSoap
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EPay_AuctionWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(EPay_AuctionWSSoapClient.GetBindingForEndpoint(endpointConfiguration), EPay_AuctionWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EPay_AuctionWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EPay_AuctionWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EPay_AuctionWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EPay_AuctionWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EPay_AuctionWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public EpayAuctionWs.StartPaymentResponse StartPayment(EpayAuctionWs.StartPaymentRequest request)
        {
            return base.Channel.StartPayment(request);
        }
        
        public System.Threading.Tasks.Task<EpayAuctionWs.StartPaymentResponse> StartPaymentAsync(EpayAuctionWs.StartPaymentRequest request)
        {
            return base.Channel.StartPaymentAsync(request);
        }
        
        public EpayAuctionWs.GetPendingPaymentsResponse GetPendingPayments(EpayAuctionWs.GetPendingPaymentsRequest request)
        {
            return base.Channel.GetPendingPayments(request);
        }
        
        public System.Threading.Tasks.Task<EpayAuctionWs.GetPendingPaymentsResponse> GetPendingPaymentsAsync(EpayAuctionWs.GetPendingPaymentsRequest request)
        {
            return base.Channel.GetPendingPaymentsAsync(request);
        }
        
        public EpayAuctionWs.AcceptPaymentResponse AcceptPayment(EpayAuctionWs.AcceptPaymentRequest request)
        {
            return base.Channel.AcceptPayment(request);
        }
        
        public System.Threading.Tasks.Task<EpayAuctionWs.AcceptPaymentResponse> AcceptPaymentAsync(EpayAuctionWs.AcceptPaymentRequest request)
        {
            return base.Channel.AcceptPaymentAsync(request);
        }
        
        public EpayAuctionWs.RefundPaymentResponse RefundPayment(EpayAuctionWs.RefundPaymentRequest request)
        {
            return base.Channel.RefundPayment(request);
        }
        
        public System.Threading.Tasks.Task<EpayAuctionWs.RefundPaymentResponse> RefundPaymentAsync(EpayAuctionWs.RefundPaymentRequest request)
        {
            return base.Channel.RefundPaymentAsync(request);
        }
        
        public EpayAuctionWs.GetOrderStatusResponse GetOrderStatus(EpayAuctionWs.GetOrderStatusRequest request)
        {
            return base.Channel.GetOrderStatus(request);
        }
        
        public System.Threading.Tasks.Task<EpayAuctionWs.GetOrderStatusResponse> GetOrderStatusAsync(EpayAuctionWs.GetOrderStatusRequest request)
        {
            return base.Channel.GetOrderStatusAsync(request);
        }
        
        public EpayAuctionWs.Z160EPayCreateResponse Z160EPayCreate(EpayAuctionWs.Z160EPayCreateRequest request)
        {
            return base.Channel.Z160EPayCreate(request);
        }
        
        public System.Threading.Tasks.Task<EpayAuctionWs.Z160EPayCreateResponse> Z160EPayCreateAsync(EpayAuctionWs.Z160EPayCreateRequest request)
        {
            return base.Channel.Z160EPayCreateAsync(request);
        }
        
        public EpayAuctionWs.PCreatePayResponse PCreatePay(EpayAuctionWs.PCreatePayRequest request)
        {
            return base.Channel.PCreatePay(request);
        }
        
        public System.Threading.Tasks.Task<EpayAuctionWs.PCreatePayResponse> PCreatePayAsync(EpayAuctionWs.PCreatePayRequest request)
        {
            return base.Channel.PCreatePayAsync(request);
        }
        
        public EpayAuctionWs.PCreatePayGuideResponse PCreatePayGuide(EpayAuctionWs.PCreatePayGuideRequest request)
        {
            return base.Channel.PCreatePayGuide(request);
        }
        
        public System.Threading.Tasks.Task<EpayAuctionWs.PCreatePayGuideResponse> PCreatePayGuideAsync(EpayAuctionWs.PCreatePayGuideRequest request)
        {
            return base.Channel.PCreatePayGuideAsync(request);
        }
        
        public EpayAuctionWs.PCreateComisPayResponse PCreateComisPay(EpayAuctionWs.PCreateComisPayRequest request)
        {
            return base.Channel.PCreateComisPay(request);
        }
        
        public System.Threading.Tasks.Task<EpayAuctionWs.PCreateComisPayResponse> PCreateComisPayAsync(EpayAuctionWs.PCreateComisPayRequest request)
        {
            return base.Channel.PCreateComisPayAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EPay_AuctionWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.EPay_AuctionWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EPay_AuctionWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.55.27/TestCBSProxyWS/EPay_AuctionWS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.EPay_AuctionWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.55.27/TestCBSProxyWS/EPay_AuctionWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            EPay_AuctionWSSoap,
            
            EPay_AuctionWSSoap12,
        }
    }
}
