//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthWS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://hcsbk.kz/", ConfigurationName="TokenAuthWS.TokenAuthWSSoap")]
    public interface TokenAuthWSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/UserLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TokenAuthWS.UserLoginResponse UserLogin(TokenAuthWS.UserLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/UserLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<TokenAuthWS.UserLoginResponse> UserLoginAsync(TokenAuthWS.UserLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/ChangePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TokenAuthWS.ChangePasswordResponse ChangePassword(TokenAuthWS.ChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/ChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<TokenAuthWS.ChangePasswordResponse> ChangePasswordAsync(TokenAuthWS.ChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/CheckToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TokenAuthWS.CheckTokenResponse CheckToken(TokenAuthWS.CheckTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hcsbk.kz/CheckToken", ReplyAction="*")]
        System.Threading.Tasks.Task<TokenAuthWS.CheckTokenResponse> CheckTokenAsync(TokenAuthWS.CheckTokenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserLogin", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class UserLoginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string SystemID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public string Login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=2)]
        public string Password;
        
        public UserLoginRequest()
        {
        }
        
        public UserLoginRequest(string SystemID, string Login, string Password)
        {
            this.SystemID = SystemID;
            this.Login = Login;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserLoginResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class UserLoginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string UserLoginResult;
        
        public UserLoginResponse()
        {
        }
        
        public UserLoginResponse(string UserLoginResult)
        {
            this.UserLoginResult = UserLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePassword", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class ChangePasswordRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string SystemID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=1)]
        public string Login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=2)]
        public string OldPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=3)]
        public string NewPassword;
        
        public ChangePasswordRequest()
        {
        }
        
        public ChangePasswordRequest(string SystemID, string Login, string OldPassword, string NewPassword)
        {
            this.SystemID = SystemID;
            this.Login = Login;
            this.OldPassword = OldPassword;
            this.NewPassword = NewPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePasswordResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class ChangePasswordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public bool ChangePasswordResult;
        
        public ChangePasswordResponse()
        {
        }
        
        public ChangePasswordResponse(bool ChangePasswordResult)
        {
            this.ChangePasswordResult = ChangePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckToken", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class CheckTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public string Token;
        
        public CheckTokenRequest()
        {
        }
        
        public CheckTokenRequest(string Token)
        {
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckTokenResponse", WrapperNamespace="http://hcsbk.kz/", IsWrapped=true)]
    public partial class CheckTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hcsbk.kz/", Order=0)]
        public bool CheckTokenResult;
        
        public CheckTokenResponse()
        {
        }
        
        public CheckTokenResponse(bool CheckTokenResult)
        {
            this.CheckTokenResult = CheckTokenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface TokenAuthWSSoapChannel : TokenAuthWS.TokenAuthWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class TokenAuthWSSoapClient : System.ServiceModel.ClientBase<TokenAuthWS.TokenAuthWSSoap>, TokenAuthWS.TokenAuthWSSoap
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TokenAuthWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(TokenAuthWSSoapClient.GetBindingForEndpoint(endpointConfiguration), TokenAuthWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TokenAuthWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TokenAuthWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TokenAuthWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TokenAuthWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TokenAuthWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public TokenAuthWS.UserLoginResponse UserLogin(TokenAuthWS.UserLoginRequest request)
        {
            return base.Channel.UserLogin(request);
        }
        
        public System.Threading.Tasks.Task<TokenAuthWS.UserLoginResponse> UserLoginAsync(TokenAuthWS.UserLoginRequest request)
        {
            return base.Channel.UserLoginAsync(request);
        }
        
        public TokenAuthWS.ChangePasswordResponse ChangePassword(TokenAuthWS.ChangePasswordRequest request)
        {
            return base.Channel.ChangePassword(request);
        }
        
        public System.Threading.Tasks.Task<TokenAuthWS.ChangePasswordResponse> ChangePasswordAsync(TokenAuthWS.ChangePasswordRequest request)
        {
            return base.Channel.ChangePasswordAsync(request);
        }
        
        public TokenAuthWS.CheckTokenResponse CheckToken(TokenAuthWS.CheckTokenRequest request)
        {
            return base.Channel.CheckToken(request);
        }
        
        public System.Threading.Tasks.Task<TokenAuthWS.CheckTokenResponse> CheckTokenAsync(TokenAuthWS.CheckTokenRequest request)
        {
            return base.Channel.CheckTokenAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TokenAuthWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.TokenAuthWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TokenAuthWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.55.27/TestCBSProxyWS/TokenAuthWS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.TokenAuthWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.55.27/TestCBSProxyWS/TokenAuthWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            TokenAuthWSSoap,
            
            TokenAuthWSSoap12,
        }
    }
}
